/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c604e0fb2de59cb4d670dd358b43172d)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	KAD_PRODUCTS_ENVIRONMENT: "integration" | "staging" | "production" | "development";
	LOG_LEVEL: "debug";
	LOG_LEVEL_TASK_OVERRIDE: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface IntegrationEnv {
		ASSETS: Fetcher;
		KAD_PRODUCTS_ENVIRONMENT: "integration";
	}
	interface StagingEnv {
		ASSETS: Fetcher;
		KAD_PRODUCTS_ENVIRONMENT: "staging";
	}
	interface ProductionEnv {
		ASSETS: Fetcher;
		KAD_PRODUCTS_ENVIRONMENT: "production";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KAD_PRODUCTS_ENVIRONMENT" | "LOG_LEVEL" | "LOG_LEVEL_TASK_OVERRIDE">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}